version: '3.7'
services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cherrab123
      POSTGRES_DB: siem
    ports:
      - "5433:5433"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  spark-app:
    build: .
    depends_on:
      - postgres
      - kafka
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5433
      - POSTGRES_DB=siem
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cherrab123
      - KAFKA_BROKER=kafka:9092
